// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxXDYn0b-Q-t3TQG6DElGZYqcaKJBCk5Y',
    appId: '1:979461619749:web:379c11efceef9eef403fcc',
    messagingSenderId: '979461619749',
    projectId: 'messages-4aa4f',
    authDomain: 'messages-4aa4f.firebaseapp.com',
    storageBucket: 'messages-4aa4f.appspot.com',
    measurementId: 'G-XYT70J35C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs_pWN5MPO2Ss69uFa6R-DFt3izlq8eiM',
    appId: '1:979461619749:android:6a5b982dbbc8ede9403fcc',
    messagingSenderId: '979461619749',
    projectId: 'messages-4aa4f',
    storageBucket: 'messages-4aa4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsR1xteeLuMBo1qvvPuKraIuY9rOTPEgc',
    appId: '1:979461619749:ios:ef6da5236ddc22eb403fcc',
    messagingSenderId: '979461619749',
    projectId: 'messages-4aa4f',
    storageBucket: 'messages-4aa4f.appspot.com',
    iosBundleId: 'com.glare.messages',
  );
}
